-- Миграция: добавить расширенные нутриенты в таблицу meals
-- Запустить на продакшен-базе ПЕРЕД деплоем нового кода

ALTER TABLE meals ADD COLUMN IF NOT EXISTS fiber FLOAT DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS sugar FLOAT DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS sugar_alcohols FLOAT DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS net_carbs FLOAT DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS saturated_fat FLOAT DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS unsaturated_fat FLOAT DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS glycemic_index INT DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS meal_type VARCHAR(20) DEFAULT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS dish_name VARCHAR(255) DEFAULT NULL;
